Create  2개 이하로 다른 비트, 생성 및 풀이 추가
codeisneverodd/programmers-coding-test pull request #38
Opened 2022-04-20 01:43 UTC by le2sky

2022-04-20 06:41 UTC, codeisneverodd requested changes
@le2sky 좋은 코드 감사합니다! 파일명과 주석 형식도 정확하게 맞추어주셨군요!
하지만 해당 풀이가 통과되지 않아 수정 요청을 드립니다! 리뷰 내용을 확인해주시고 변경 부탁드립니다 😄

2022-04-20 06:41 UTC, codeisneverodd commented on level-2/2개-이하로-다른-비트.js
> +  return answer;
기여해주셔서 감사합니다! 감사한 마음을 담아 리뷰 남깁니다 😁

`let answer = []`를 `const answer = []`로 변경하시는 것도 좋아보입니다! 
`answer = [3]`과 같이 직접 배열 콜스택에 들어있는 배열의 메모리힙 주소의 값을 변경하는 것이 아니라, push 등과 같이 메모리 힙에 들어있는 값만을 바꾸는 것이라면 let보다는 const로 선언하는 것이 사이드 이펙트(생각치 못한 동작)를 막기에 좋은 것으로 알고있습니다!

참고링크
https://curryyou.tistory.com/276

2022-04-20 06:41 UTC, codeisneverodd commented on level-2/2개-이하로-다른-비트.js
> +  numbers.forEach((num) => {
`numbers`라는 변수가 선언되어 있지 않아, 해설이 통과되지 않습니다! 확인 후 변경해주시면 감사하겠습니다 😄

2022-04-20 06:45 UTC, codeisneverodd commented on level-2/2개-이하로-다른-비트.js
> +  numbers.forEach((num) => {
`numbers -> n` 으로 변경하면 되지 않을까 생각합니다!

2022-04-20 12:09 UTC, le2sky commented
@codeisneverodd   수정했습니다! 간과하기 쉬운 디테일한 피드백 감사드립니다😎

2022-04-21 04:35 UTC, codeisneverodd commented
@le2sky 기여해주셔서 감사합니다! Merge 되었습니다 😄

2022-04-21 04:35 UTC, merged